// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpmr9-2QyoubOcvaVtvdc_umYiyqVPW1A',
    appId: '1:645996289423:android:bdcf0cc3776a85db8dbffa',
    messagingSenderId: '645996289423',
    projectId: 'a-simple-flutter-arduino-test',
    databaseURL: 'https://a-simple-flutter-arduino-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'a-simple-flutter-arduino-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbblBkneAnPCLOyaCda_KQ4sLqkR5yo8',
    appId: '1:645996289423:ios:0e286bcc18ffc3f18dbffa',
    messagingSenderId: '645996289423',
    projectId: 'a-simple-flutter-arduino-test',
    databaseURL: 'https://a-simple-flutter-arduino-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'a-simple-flutter-arduino-test.appspot.com',
    iosClientId: '645996289423-qrtseebn147h1r1dt7ftoh5f2jdbfgnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
